import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/style/global.scss";
import "@/style/controls.scss";
import "@/style/dialogs.scss";
import { cookies } from "next/headers";
import { CookiesProvider } from 'next-client-cookies/server';
import { MainContextProvider } from "@/context/MainContext";
import MainContainer from "@/components/MainContainer";
import HeaderPage from "@/components/HeaderPage";
import LeftMenuPage from "@/components/LeftMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vocabulary",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let theme = "theme-dark";
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme');
  theme = themeCookie ? themeCookie.value : "theme-dark";

  const projectIdCookie = cookieStore.get('project_id');
  const project_id = projectIdCookie?.value;

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <CookiesProvider>
        <body className={"" + theme}>
          <MainContextProvider>
            <HeaderPage></HeaderPage>
            <div className="voc-container">
              <LeftMenuPage></LeftMenuPage>
              <div className="voc-data">
                <MainContainer project_id={ project_id || "" }>
                  {children}
                </MainContainer>
              </div>
            </div>
          </MainContextProvider>
        </body>
      </CookiesProvider>
    </html>
  );
}
